---
title: "Problem-2"
latex_engine: lualatex
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#install.packages("R.utils")
library(R.utils)
Standard= c(2.5, 3.4, 2.9, 4.1, 5.3, 3.4, 1.9, 3.3, 1.8 )
Additive=c(3.5, 6.3, 4.2, 4.3, 3.8, 5.7, 4.4, 0, 0)
diff=Additive - Standard
sttrue= mean(diff)
n=length(diff)
nf=2^n-1
st=numeric(nf)
stat = numeric(n)

for (i in 0:nf)
  { rearr=intToBin(i) 
nn=nchar(rearr)
u=strrep("0", n-nn)
rearr=paste(u,rearr,sep="")
for (j in 1:n){stat[j]=ifelse(substr(rearr,j,j)==0, diff[j], -diff[j])}
st[i]=mean(stat)
}
pvalue <-length(st[st<=sttrue])/(2^n) # p-value
pvalue
hist(stat)
points(sttrue,0,pch = 16,
       col = "blue")
#since the p-value is larger,we have enough evidence to support the 
#null hypothesis therefore,the null hypothesis is not rejected,so we can conclude
# that the additive is not effective.

 
#(b) Explore several statistics in order to perform the permutation test.
#What is the final conclusion?
#we are going to use several statistic like pearson correlation coefficient and 
#spearman correlation coefficient
Standard= c(2.5, 3.4, 2.9, 4.1, 5.3, 3.4, 1.9, 3.3, 1.8 )
Additive=c(3.5, 6.3, 4.2, 4.3, 3.8, 5.7, 4.4, 0, 0)
diff=Additive - Standard
n=length(diff)
sttrue1= median(diff)
n=length(diff)
nf=2^n-1
st1=numeric(nf)
stat = numeric(n)

for (i in 0:nf)
{ rearr=intToBin(i) 
nn=nchar(rearr)
u=strrep("0", n-nn)
rearr=paste(u,rearr,sep="")
for (j in 1:n){stat[j]=ifelse(substr(rearr,j,j)==0, diff[j], -diff[j])}
st1[i]=median(stat)
}
pvalue1 <-length(st1[st1<=sttrue1])/(2^n) # p-value
pvalue1
hist(stat)
points(sttrue1,0,pch = 16,
       col = "red")

#in this case,using different statistic the p-value is also larger,we 
#have enough evidence to support the null hypothesis
#therefore,the null hypothesis is not rejected,so we can conclude that
#there does not exist a significant difference before and after the additive
#that is the additive is not effective 


```

